### ISSUE TITLE
driver registration doesn't work on microk8s snap

### ISSUE THREAD

**Issue by chornlgscout** [openebs/zfs-localpv#113]
Registration is sensibly targeted to /var/lib/kubelet, but the directory actually used by microk8s snap is /var/snap/microk8s/common/var/lib/kubelet. I resolved this by symlinking the actual location to the expected location.

**Comment by pawanpraka1** [comment]
Thanks @chornlgscout. Thanks for reporting this issue. Yes, the driver expects the default mount path to be in "/var/lib/kubelet". But if it is different then we can modify the operator accordingly : https://github.com/openebs/zfs-localpv/blob/9c81ba9587f022e47985a4ac9290238f996fc317/deploy/zfs-operator.yaml#L1298

**Comment by pawanpraka1** [comment]
duplicate #112 https://github.com/openebs/zfs-localpv/issues/112

**Comment by pawanpraka1** [comment]
Tracked under https://github.com/openebs/zfs-localpv/issues/112. Closing this.
