### ISSUE TITLE
Support for deploying to CentOS

### ISSUE THREAD

**Issue by zimmertr** [openebs/zfs-localpv#119]
## Description

The `zfs-Operator` manifest is incompatible with ZFS. After deployment some hostPath references to libraries fail.

```
Warning  FailedMount  20m (x5 over 20m)    kubelet, localhost.localdomain  MountVolume.SetUp failed for volume "libzpool" : hostPath type check failed: /lib/libzpool.so.2.0.0 is not a file
  Warning  FailedMount  20m (x5 over 20m)    kubelet, localhost.localdomain  MountVolume.SetUp failed for volume "libnvpair" : hostPath type check failed: /lib/libnvpair.so.1.0.1 is not a file
```

## Context
I use CentOS/RHEL in production not Ubuntu.

## Possible Solution
This [manifest](https://gist.github.com/zimmertr/e177f4db6cea1b1960af32db210b384b) with modified libraries was sent to me via Slack and is deploying successfully.

**Comment by jlcox1970** [comment]
I am also facing issue on CentOS 8 nodes with this driver.
I see the following int the openebs-zfs-plugin container logs

time="2020-05-21T23:39:27Z" level=error msg="zfs: could not set mountpoint on dataset main/pvc-b27284ae-3033-49e3-9c18-89f0c4895fcb cmd [set mountpoint=/var/lib/kubelet/pods/e1d092c2-7120-4dd8-a0de-4b523f19b972/volumes/kubernetes.io~csi/pvc-b27284ae-3033-49e3-9c18-89f0c4895fcb/mount main/pvc-b27284ae-3033-49e3-9c18-89f0c4895fcb] error: zfs: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory\n"
22/05/2020 09:39:27

**Comment by zimmertr** [comment]
Please use the manifests and image described in t[his comment](https://github.com/openebs/zfs-localpv/issues/119#issuecomment-598032945) by @pawanpraka1 until this has been resolved upstream.

**Comment by jlcox1970** [comment]
I have used that image and the also the SC yaml that is also mentioned.
This got me to the point of no other errors in the logs apart from the above.

**Comment by jlcox1970** [comment]
finally worked this out, the image is CentOS7 based...
it has libc-2.17 and all the libs that go with that
however, I am on CentOS8 and that a libc-2.28

I can update the docker image but I need to know how to run the make file to get the zfs-driver

alternatively can I just copy that out of the existing container and into the the new one ?

**Comment by pawanpraka1** [comment]
@jlcox1970 sorry, we couldn't prioritize this in to our release. Clone this repo https://github.com/pawanpraka1/zfs-localpv and go to the CentOS branch. then Just change the image to centos8 in the docker file https://github.com/pawanpraka1/zfs-localpv/blob/centos/buildscripts/zfs-driver/Dockerfile. To create the image, you just have to do `make` to get the image.

**Comment by jlcox1970** [comment]
@pawanpraka1 thats ok and i am happy to help as this is my cluster at home :)

as for the make, I have never used go before and so I have a whole lot of errors that come up
`
--> Running go fmt
can't load package: package _/root/git/zfs-localpv/cmd: cannot find package "_/root/git/zfs-localpv/cmd" in any of:
        /usr/lib/golang/src/_/root/git/zfs-localpv/cmd (from $GOROOT)
        /root/go/src/_/root/git/zfs-localpv/cmd (from $GOPATH)
can't load package: package _/root/git/zfs-localpv/pkg/apis/openebs.io/core/v1alpha1: cannot find package "_/root/git/zfs-localpv/pkg/apis/openebs.io/core/v1alpha1" in any of:
        /usr/lib/golang/src/_/root/git/zfs-localpv/pkg/apis/openebs.io/core/v1alpha1 (from $GOROOT)
`
can you give me some points on set of a GO environment ?
thanks

**Comment by pawanpraka1** [comment]
@jlcox1970 here is the developer setup doc : https://github.com/openebs/zfs-localpv/blob/master/docs/developer-setup.md. 

I have push the centos8 image also and update the operator file with that. You can try this yaml which is using centos8 image : https://raw.githubusercontent.com/pawanpraka1/zfs-localpv/centos/deploy/zfs-operator.yaml

**Comment by jlcox1970** [comment]
@pawanpraka1 that fixed it nicely :)
I will look into the dev environment setup this weekend and make it all containerised so that I dont have to revisit it :)

**Comment by pawanpraka1** [comment]
Sure @jlcox1970 . Just to confirm, you are able to provision the volume using the latest yaml?

**Comment by pawanpraka1** [comment]
can you also also provide the below details : 
1. zfs version
2.  ldd `which zfs`
3. cat /etc/*release*

**Comment by jlcox1970** [comment]
yes the volume is provisioned
zfs-0.8.4-1.el8.x86_64

linux-vdso.so.1 (0x00007fff74dcb000)
        libnvpair.so.1 => /lib/libnvpair.so.1 (0x00007f7523620000)
        libuutil.so.1 => /lib/libuutil.so.1 (0x00007f7523410000)
        libzfs.so.2 => /lib/libzfs.so.2 (0x00007f7523190000)
        libzfs_core.so.1 => /lib/libzfs_core.so.1 (0x00007f7522f88000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f7522d30000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f75229a8000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f7522710000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f7522230000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f7522020000)
        libtirpc.so.3 => /lib64/libtirpc.so.3 (0x00007f7521de8000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00007f7521bc0000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f75219b8000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f75217a0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7521580000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f75211b8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7523a60000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7520fa0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f7520d98000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f7520b48000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f7520858000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f7520638000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f7520430000)
        libmount.so.1 => /lib64/libmount.so.1 (0x00007f75201d0000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f751ffb8000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f751fdb0000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f751fb98000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f751f968000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f751f6e0000)

CentOS Linux release 8.1.1911 (Core)

**Comment by pawanpraka1** [comment]
@zimmertr, @jlcox1970  I am working on a change(https://github.com/pawanpraka1/zfs-localpv/commit/6c567bd9681403942640a1f03ccf51d774ccfe87) which can work for both ubuntu and centos. I have tested it on ubuntu, and it seems to be working. I need one help/favor from you guys, if you can test this on centos7 and centos8 and if it is working then I will upstream this change.  

https://raw.githubusercontent.com/pawanpraka1/zfs-localpv/lib/deploy/zfs-operator.yaml

**Comment by zimmertr** [comment]
I have actually moved away from CentOS 7 to Flatcar Linux since making this post and do not have a server available to test anymore. If @jlcox1970 is unable to as well, I could probably spin something up in a VM though. It just won't resemble a production environment any longer.

**Comment by pawanpraka1** [comment]
@zimmertr thanks. Flatcar will also be supported if the libraries required for zfs is in /lib or /lib64 and binary is installed at /sbin/zfs or /usr/sbin/zfs. If that is the case then same yaml will work, otherwise we have to make little modification to the yaml and it should just work.
We can check 2 things to confirm that 

1. `which zfs` <== to check the binary path
2. ldd `which zfs` <== to check the libraries

**Comment by jlcox1970** [comment]
sorry on the delay on this but work......
got to testing and found that the openebs-zfs-plug keeps failing and
the only thing in the logs are

*** stack smashing detected ***: <unknown> terminated


Jason

**Comment by pawanpraka1** [comment]
@jlcox1970 thanks for helping me with the testing. It seems like there is more work needs to be done in this. I should probably restrict the host libraries to zfs binary only. Currently the whole pod is exposed to the host libraries and that is probably causing the issue. Let me fix that. Thanks again @jlcox1970 .

**Comment by pawanpraka1** [comment]
@jlcox1970, sorry for the delay, Please see the below yaml works for you

for CentOS7 =>

https://raw.githubusercontent.com/pawanpraka1/zfs-localpv/centos/deploy/operators/centos7/zfs-operator.yaml

CentOS8 =>

https://raw.githubusercontent.com/pawanpraka1/zfs-localpv/centos/deploy/operators/centos8/zfs-operator.yaml

**Comment by pawanpraka1** [comment]
We have upstreamed the centos7 and centos8 yaml here 

https://raw.githubusercontent.com/openebs/zfs-localpv/master/deploy/operators/centos7/zfs-operator.yaml

https://raw.githubusercontent.com/openebs/zfs-localpv/master/deploy/operators/centos8/zfs-operator.yaml

**Comment by pawanpraka1** [comment]
We have merged a PR https://github.com/openebs/zfs-localpv/pull/204 to make the ZFS operator yaml not agnostic to the underlying Operation system. Now we can use the same Operator yaml (https://github.com/openebs/zfs-localpv/blob/master/deploy/zfs-operator.yaml) of all the Operating systems.
