### ISSUE TITLE
refactoring needed to add support for go modules.

### ISSUE THREAD

**Issue by vaniisgh** [openebs/zfs-localpv#129]
The following projects need help with refactoring to use go modules. 
[ ] https://github.com/openebs/zfs-localpv
[ ] https://github.com/openebs/node-disk-manager
[WIP] https://github.com/openebs/maya

_Originally posted by @kmova in https://github.com/openebs/openebs/issues/3040#issuecomment-630568725_

**Comment by pawanpraka1** [comment]
duplicate of https://github.com/openebs/zfs-localpv/issues/126.
