### ISSUE TITLE
remove MountInfo struct from the API file

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/zfs-localpv#142]
**Describe the problem/challenge you have**

MountInfo struct is in memory struct used to keep the information related to mounting the volume. It should not be there in the versioned api file. 

https://github.com/openebs/zfs-localpv/blob/307861282a5976e4a4a8e2d52f5f2fe94b9d8305/pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go#L46

**Describe the solution you'd like**

Move the MountInfo struct to the pkg/zfs/mount.go file from pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go

**Comment by codegagan** [comment]
I am looking into this.

**Comment by codegagan** [comment]
moving only MountInfo is causing cyclic imports, because there are lot of structs like ZFSVolume in apis package which are required in zfs package. if MountInfo is moved, we need to add zfs package import to api.

@pawanpraka1 Please suggest some solution for this.

**Comment by pawanpraka1** [comment]
@codegagan once you remove the MountInfo struct you should run `make kubegen`. There are few autogenerated code because of thsi is part of api. Once you move it to pkg/zfs/mount.go, and run `make kubegen` there should not be any reference of it in api.

Also since we have v1alpha1 and v1 api version now. So we have to remove it from two files : 
pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go
pkg/apis/openebs.io/zfs/v1/zfsvolume.go

**Comment by codegagan** [comment]
Thanks, that was helpful, raised the PR.
