### ISSUE TITLE
readme need to be updated

### ISSUE THREAD

**Issue by w3aman** [openebs/zfs-localpv#163]
**What steps did you take and what happened:**

I tried to apply the zfs-operator file on k8s version 1.15. but yaml was not applying giving out the error.
```
namespace/openebs created
customresourcedefinition.apiextensions.k8s.io/zfsvolumes.zfs.openebs.io created
customresourcedefinition.apiextensions.k8s.io/zfssnapshots.zfs.openebs.io created
error: error validating "https://raw.githubusercontent.com/openebs/zfs-localpv/master/deploy/zfs-operator.yaml": error validating data: ValidationError(CSIDriver.spec): unknown field "volumeLifecycleModes" in io.k8s.api.storage.v1beta1.CSIDriverSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**What did you expect to happen:**

As readme says supported on k8s 1.14+ but looks like `volumeLIfecycleModes` field works only after k8s 1.16
And
OS support is also mentioned only ubuntu 18.04 but i could see CentOS 7/8 support is now available.

So either have to fix the above error or update the readme accordingly.
say, 
k8s :  1.16+ and OS: ubuntu 18.04, 16.04, centos 7/8
                                            OR
fix this issue and k8s: 1.14+ and OS: ubuntu 18.04, 16.04, centsos 7/8

**Comment by pawanpraka1** [comment]
We also need to improve the setup part and add details about how can we setup the zpool. Also, if possible, we can add support to automatically setup the pool.
