### ISSUE TITLE
Use ZFS dataset instead of ZPOOL

### ISSUE THREAD

**Issue by sonicaj** [openebs/zfs-localpv#189]
**Describe the problem/challenge you have**

Hello. I have been exploring storage solutions available in for k8s using ZFS and came across this. It appears that in order to use zfs-localpv, we require a dedicated ZPOOL on all nodes. Our use case is basically a single node cluster where we are using k3s. It would be great if I could have it confined to use a zfs dataset instead of specifying a zpool.

I am not sure if we already have this functionality, in that case can you please point me to the docs ?

**Describe the solution you'd like**

It would be great if we are able to specify a zfs dataset instead of zpool and then all the magic done by `zfs-localpv` happens under that zfs dataset. Right now it uses a root dataset where it creates children and manages them.

**Environment:**
- ZFS-LocalPV version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
K3s
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by pawanpraka1** [comment]
@sonicaj we can give parent dataset also in the poolname. It just works. Please make sure that dataset is already created.

```apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
parameters:
  poolname: "zfspv-pool/dataset"
provisioner: zfs.csi.openebs.io
```

**Comment by sonicaj** [comment]
That's just awesome. Thank you @pawanpraka1 for pointing it out.

**Comment by sonicaj** [comment]
Btw it would be nice if we could mention it in README or somewhere in the docs. Would you like me to make a small PR for README ? Should be a one line change

**Comment by pawanpraka1** [comment]
yes, sure @sonicaj, please raise the PR.
