### ISSUE TITLE
Mismatch between CRs and ZFS volumes on node

### ISSUE THREAD

**Issue by spencergilbert** [openebs/zfs-localpv#195]
**What steps did you take and what happened:**
Currently running 0.6.1, noticed that the on disk ZFS results didn't match with the results returned from `kubectl get zfsvolumes -A`

**What did you expect to happen:**
1:1 matching

**The output of the following commands will help us better understand what's going on**:
`zfs list -t all`

```
local/pv/pvc-086ec32f-cce0-4009-8948-1ab6d4ccb839                                             7.59G   592G     7.59G  /var/lib/kubelet/pods/c6fa7984-2760-47f7-a105-3f2aa079db3e/volumes/kubernetes.io~csi/pvc-086ec32f-cce0-4009-8948-1ab6d4ccb839/mount
local/pv/pvc-370d7921-6a33-4336-ab85-2ddd789c576f                                             4.84M  10.0G     4.84M  /var/lib/kubelet/pods/64222e8a-8690-450b-8bc5-58868d8aa6bd/volumes/kubernetes.io~csi/pvc-370d7921-6a33-4336-ab85-2ddd789c576f/mount
local/pv/pvc-e1275578-6abd-4401-8402-9eb1298cfdb7                                             11.4G  88.6G     11.4G  /var/lib/kubelet/pods/e70a4494-14e7-481a-8d0c-424d20d1d876/volumes/kubernetes.io~csi/pvc-e1275578-6abd-4401-8402-9eb1298cfdb7/mount
local/pv/pvc-e3f70edf-9479-4e0b-bc21-0b00ee426307                                              204K  1024M      204K  /var/lib/kubelet/pods/7cf7f87d-fc90-4c21-a1c8-e7a605cf16bf/volumes/kubernetes.io~csi/pvc-e3f70edf-9479-4e0b-bc21-0b00ee426307/mount
```

```
❯ kubectl get zfsvolumes.zfs.openebs.io -A | rg textile
openebs     pvc-04230116-1719-4fc9-87e9-6bcbbb1440ac   local/pv   halfling-textile   8589934592                                 zfs                         112d
openebs     pvc-086ec32f-cce0-4009-8948-1ab6d4ccb839   local/pv   halfling-textile   644245094400                               zfs                         11d
openebs     pvc-370d7921-6a33-4336-ab85-2ddd789c576f   local/pv   halfling-textile   10737418240                                zfs                         43d
openebs     pvc-66cb5b8b-f446-414d-b451-8ddc66a1cdfe   local/pv   halfling-textile   8589934592                                 zfs                         112d
openebs     pvc-e1275578-6abd-4401-8402-9eb1298cfdb7   local/pv   halfling-textile   107374182400                               zfs                         43d
openebs     pvc-e3f70edf-9479-4e0b-bc21-0b00ee426307   local/pv   halfling-textile   1073741824                                 zfs                         29d
```
ZFSVolumes.yaml: https://gist.github.com/spencergilbert/c4008694b7b19f224a3d7c3df535286d

openebs-zfs-plugin logs:
https://gist.github.com/spencergilbert/21a5b84bbdc08962edbfd18093ff5ba0

**Environment:**
- ZFS-LocalPV version: 0.6.1
- Kubernetes version (use `kubectl version`): 1.18.6
- Kubernetes installer & version: rancher 2.4.5
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

**Comment by pawanpraka1** [comment]
@spencergilbert can I get one more output :
```
zpool history -li | grep -e pvc-04230116-1719-4fc9-87e9-6bcbbb1440ac -e pvc-66cb5b8b-f446-414d-b451-8ddc66a1cdfe
```

**Comment by spencergilbert** [comment]
no results returned

**Comment by pawanpraka1** [comment]
the below two volumes are not present :-
1. pvc-04230116-1719-4fc9-87e9-6bcbbb1440ac
2. pvc-66cb5b8b-f446-414d-b451-8ddc66a1cdfe

They both are created on 2020-05-05 (112 days old). @spencergilbert by any chance we recreated the ZFS pool? zpool history can help you find the pool creation time.

if that is not the case can we check if corresponding PV is present? can I get the PV yaml :-
```
kubectl get pv pvc-04230116-1719-4fc9-87e9-6bcbbb1440ac pvc-66cb5b8b-f446-414d-b451-8ddc66a1cdfe -oyaml
```

**Comment by spencergilbert** [comment]
sorry @pawanpraka1 this dropped off my radar - this does seem to be from us rebuilding nodes. Don't know if you want to try and handle that in the provisioner

**Comment by pawanpraka1** [comment]
that explains @spencergilbert. We should clean everything before rebuilding the node. Closing this issue.
