### ISSUE TITLE
Snapshot data is different after restoring the zfs-localpv backup

### ISSUE THREAD

**Issue by w3aman** [openebs/zfs-localpv#207]
**What happened:**

I provisioned the zfs-localpv and busybox application is consuming it. I dumped some data and after that i took the volume snapshot. So suppose i took the snapshot S1 of data D1.  
Now more data is dumped say D2. Now volume is having D1+D2 data in total.
After that backup is created. So it should be consisiting of total data of D1+D2 and one volume snapshot S1 of D1 data.

When backup is restored in some different namespace, Application mount point have the total data and we have successfully restored the vol-snapshot S1 also in that namespace.
But when we try to clone that snapshot, my clone volume is having data total D1+D2 data but clone should be consisting of data on which snapshot was taken i.e. data D1. it should not have the data which was dumped after taking the snapshot.

Here looks like while taking the backup snapshot was backed up with whole data upto the backup start time, instead of only that data for which snapshot was created.

**Comment by pawanpraka1** [comment]
it is a limitation here, we can do either these two things 
1.    exclude the volumesnapshot during backup/restore
 2.   if we are restoring the snapshot, it may not point to the same data as the source snapshot.
