### ISSUE TITLE
Validations - stop from making accidental deletions

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/zfs-localpv#218]
We need a way to stop accidental "openebs" namespace or CR deletions. We need a webhook or OPA to validate the deletion request.

**Comment by RealHarshThakur** [comment]
@pawanpraka1 Would adding a finalizer work?

**Comment by pawanpraka1** [comment]
@RealHarshThakur that will not help here as CR will be marked for deletion which is what we want to avoid here.

**Comment by Abhinandan-Purkait** [comment]
There aren't much reported instances of this, so this might not be an important issue to tackle.  Also, there isn't any plan to take this up in the future roadmap. Feel free to open if this is needed. Thanks
