### ISSUE TITLE
Backup/Restore without velero dependency

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/zfs-localpv#219]
ZFS-LocalPV has added supports for velero to do the backup and restore. But actually it is not really dependant on velero to do that. Add a steps/doc/blog to do the backup and restore without velero.

**Comment by almereyda** [comment]
If you know how this is been done, can you write a little outline naming the individual steps, that are generic and independent from Velero to you? I'm interested in seeing generic approaches to backing up PVs supported by ZFS, which are not tied to a specific vendor's application.

Also [syncoid](https://github.com/jimsalterjrs/sanoid/) comes to mind, which is also suggested in https://github.com/openebs/zfs-localpv/issues/291#issuecomment-875740462 for an in-tree support.

**Comment by sinhaashish** [comment]
there is a design docs which is merged here https://github.com/openebs/zfs-localpv/pull/336.

**Comment by avishnu** [comment]
Using a solution like Velero has its advantages like being able to selectively backup the configuration and manifest data along-with the volume data. Besides, Velero plug-ins allow one to integrate more natively with the underlying storage provider features (zfs send/recv in case of ZFS).
