### ISSUE TITLE
add go report card badge for ZFS-LocalPV

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/zfs-localpv#222]
**Describe the problem/challenge you have**

We need to have a go report card added in the README of the repo.

**Describe the solution you'd like**

We need to add below badge in the README.md file of the repo (https://github.com/openebs/zfs-localpv/blob/master/README.md).

```
[![Go Report](https://goreportcard.com/badge/github.com/openebs/zfs-localpv)](https://goreportcard.com/report/github.com/openebs/zfs-localpv)
```

**Comment by Naveenkhasyap** [comment]
@pawanpraka1 can i take this up ?

**Comment by pawanpraka1** [comment]
sure @Naveenkhasyap.

**Comment by pawanpraka1** [comment]
fixed via https://github.com/openebs/zfs-localpv/pull/223
