### ISSUE TITLE
ZFS properties

### ISSUE THREAD

**Issue by ThisIsQasim** [openebs/zfs-localpv#268]
Is there a way to set custom properties for the zfs child volumes created? I am looking to set `readlimit` and `writelimit` on individual pods to prevent them from hogging resources from pods on the same host.

**Comment by pawanpraka1** [comment]
@ThisIsQasim Which ZFS version you are using? Does OpenZFS supports setting `readlimit` and `writelimit` on the dataset?

**Comment by ThisIsQasim** [comment]
So I checked and apparently these properties are only available on Solaris and not implemented in OpenZFS. 
Sorry for wasting your time. Thank you for the awesome project though!
