### ISSUE TITLE
Support fsGroup?

### ISSUE THREAD

**Issue by ngbrown** [openebs/zfs-localpv#282]
**Describe the problem/challenge you have**
I setup zfs-localpv to use with [prometheus helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack). However, once I setup the volume claim, I got this error when runing the prometheus pod:

```
level=error ts=2021-02-02T00:10:18.831Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
```

Prometheus runs it's pod with the following as defaults:

```yml
    securityContext:
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
```

I also tried adding `fsGroupChangePolicy: "Always"` but that didn't change the results.

I finally got it working with an init container running as root and running `chown` to set all the files to the expected user and group.

zfs-localpv doesn't seem to support `fsGroup` as expected. In the [CSIDriverSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#csidriver-v1beta1-storage-k8s-io), I noticed that the `fsGroupPolicy` is marked as alpha, so I thought it might not be implemented.

**Describe the solution you'd like**
I would like `fsGroup` to be handled and `fsGroupPolicy` report a [supported value](https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#csidriver-fsgrouppolicy-api).

**Anything else you would like to add:**

The Kubernetes [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) article has a demo that can be adapted. Attached is the adapted `.yaml` and these commands show the problem:

[security-context-demo.yaml.txt](https://github.com/openebs/zfs-localpv/files/5908534/security-context-demo.yaml.txt)

```
$ kubectl apply -f security-context-demo.yaml
persistentvolumeclaim/security-context-demo-pvc created
pod/security-context-demo created
$ kubectl get pod security-context-demo
NAME                    READY   STATUS    RESTARTS   AGE
security-context-demo   1/1     Running   0          7s
$ kubectl exec -it security-context-demo -- sh
/ $ cd data
/data $ ls -al
total 9
drwxr-xr-x    3 root     root          4096 Feb  2 03:31 .
drwxr-xr-x    1 root     root          4096 Feb  2 03:31 ..
drwxr-xr-x    3 root     root          1024 Feb  2 03:31 demo
/data $ cd demo
/data/demo $ ls -al
total 17
drwxr-xr-x    3 root     root          1024 Feb  2 03:31 .
drwxr-xr-x    3 root     root          4096 Feb  2 03:31 ..
drwx------    2 root     root         12288 Feb  2 03:31 lost+found
/data/demo $ touch a
touch: a: Permission denied
/data/demo $
```

**Environment:**
- ZFS-LocalPV version: ZFS Driver Version :- 1.3.0 - commit :- bd6df9b31dba399551355d9e9b03b2122ce9ef98
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:50:46Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: MicroK8s v1.20.1 (1910)
- Cloud provider or hardware configuration: Local Hyper-V
- OS (e.g. from `/etc/os-release`): 

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by pawanpraka1** [comment]
@ngbrown can you update the csi drive spec (https://github.com/openebs/zfs-localpv/blob/master/deploy/zfs-operator.yaml#L1044) and add ` fsGroupPolicy: File` and see if that is working.
```
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: zfs.csi.openebs.io
spec:
  # do not require volumeattachment
  attachRequired: false
  podInfoOnMount: false
  fsGroupPolicy: File
```

**Comment by pawanpraka1** [comment]
@ngbrown I tested this on my lab cluster which is running with k8s 1.20. The above is working file. I noticed that the default fsGroupPolicy is `ReadWriteOnceWithFSType` which means that it will work only if fstype is provided in the storageclass. So in the above solution I suggested to use fsGroupPolicy as `File` which will apply fsgroup , regardless of the filesystem type or PersistentVolumeClaim’s access mode. So if you are not providing fstype in the storageclass the still want fsgroup to be applied then you need to change the policy to File as suggested above. 

Second way is to provided the fstype in the storageclass, and since CSIDRiver has fsGroupPolicy  as `ReadWriteOnceWithFSType` so it should work for you without modifying anything else. Can you please verify this?

```
$ kubectl get csidrivers.storage.k8s.io  -oyaml
I0202 18:09:27.043230    8484 request.go:655] Throttling request took 1.168488857s, request: GET:https://10.63.10.89:6443/apis/node.k8s.io/v1?timeout=32s
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSIDriver
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1beta1","kind":"CSIDriver","metadata":{"annotations":{},"name":"zfs.csi.openebs.io"},"spec":{"attachRequired":false,"podInfoOnMount":false}}
    creationTimestamp: "2021-02-02T12:07:40Z"
    managedFields:
    - apiVersion: storage.k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:attachRequired: {}
          f:fsGroupPolicy: {}
          f:podInfoOnMount: {}
          f:volumeLifecycleModes: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-02-02T12:07:40Z"
    name: zfs.csi.openebs.io
    resourceVersion: "4882041"
    uid: 9a4f4b50-bdcf-4201-a15b-8cee70df115c
  spec:
    attachRequired: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: false
    volumeLifecycleModes:
    - Persistent
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by ngbrown** [comment]
Good catch on my StorageClass not setting `fstype`. It must have been creating the file system as `ext4`.  Without the changes to CSIDriver, I also tried re-creating the StorageClass with setting `fstype: "zfs"`, and that worked as expected.

I then tried deleting the CSIDriver and re-applied it with the change, then restarted the cluster.  New volume claims now applied the file ownership to the group, even without setting the StorageClass `fstype`.

Even though I missed setting `fstype: "zfs"`, I still think `fsGroup` should work as expected on `ext4` since it is supported.

**Comment by pawanpraka1** [comment]
Thanks for confirming this @ngbrown. `ReadWriteOnceWithFSType` make sense as each volume is examined at mount time to determine if permissions should be recursively applied. It relies on fsType defined in the storageclass and the persistent volume's accessModes should contain ReadWriteOnly. Closing this issue.
