### ISSUE TITLE
No zfs-driver version referenced within operator

### ISSUE THREAD

**Issue by mazocode** [openebs/zfs-localpv#328]
The operator yaml (version 1.5.x, 1.6.0, 1.6.1) is referencing the zfs-driver CI build (openebs/zfs-driver:ci) but it looks like there are breaking changes in 1.7 (expects --nodename instead of --nodeid) which results in an error with older versions:

> OPENEBS_NODE_NAME environment variable not set

Please add the image version to existing and new releases (ie openebs/zfs-driver:zfs-localpv-1.6.1-ci).

**Comment by pawanpraka1** [comment]
@mazocode, we have moved the operator yaml to charts repo. Please see the installation step in the release page here https://github.com/openebs/zfs-localpv/releases/tag/v1.6.0.
