### ISSUE TITLE
operator files are referencing :ci build of zfs-plugin (openebs/zfs-driver image)

### ISSUE THREAD

**Issue by mazocode** [openebs/zfs-localpv#337]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.]

Controller pod (v1.6.1) got rescheduled and boom...

E0601 16:15:26.150385       1 reflector.go:138] github.com/openebs/zfs-localpv/pkg/driver/controller.go:120: Failed to watch *v1.ZFSNode: failed to list *v1.ZFSNode: zfsnodes.zfs.openebs.istem:serviceaccount:kube-system:openebs-zfs-controller-sa" cannot list resource "zfsnodes" in API group "zfs.openebs.io" in the namespace "openebs"

**What did you expect to happen:**

 Please add a version tag to the zfs-driver image!

**Comment by pawanpraka1** [comment]
@mazocode how are you installing ZFS-LocalPV? We have fixed all the branche's operator yaml with the corresponding image tag https://github.com/openebs/zfs-localpv/issues/328.

**Comment by pawanpraka1** [comment]
@mazocode are you able to figure out the operator yaml location? Can we close this issue?

**Comment by mazocode** [comment]
@pawanpraka1 We can close this issue, thanks for updating!
