### ISSUE TITLE
Add rancher operator

### ISSUE THREAD

**Issue by joshuacox** [openebs/zfs-localpv#354]
**Add rancher operator**

In the installation docs I think there could be examples given on the alternate kubelet paths, as there is a bit of ambiguity in the docs in that there are multiple locations that kubelet is mentioned in the yaml and it is not entirely clear which ones to edit.

**Describe the solution you'd like**
I have one [here](https://gist.github.com/joshuacox/8e79ef49fe61f3a0e483175f49c41b75) for rancher I'd like to place in the docs for any subsequent rancherOS users.  I would definitely appreciate anyone who can verify my work.

**Comment by pawanpraka1** [comment]
@joshuacox is the deployment working on RancherOS with the PR you have raised? Can you test with the similar changes for LVM also (https://github.com/openebs/lvm-localpv/issues/112).

**Comment by joshuacox** [comment]
@pawanpraka1 you bet.  One quick question, do you know of the best way to go about this?  Should I try and
