### ISSUE TITLE
ZFS 2.0 support?

### ISSUE THREAD

**Issue by ThomasLohmann** [openebs/zfs-localpv#356]
Hi everyone,

do you have any plans to support ZFS version 2.0+ asap? A couple of useful features have been added to this version and the current OpenEBS ZFS Driver still only supports version 0.8. Please, see the following link for more details: https://github.com/openzfs/zfs/releases/tag/zfs-2.0.0

Best regards,
Thomas

**Comment by pawanpraka1** [comment]
@ThomasLohmann have you tried with ZFS 2.0. I guess it should work without any issue.

**Comment by pawanpraka1** [comment]
@grouchojeff have you tried ZFS-LocalPV with ZFS 2.0?

**Comment by ThomasLohmann** [comment]
@pawanpraka1 not yet. Since we have a Kubernetes cluster on bare-metal and it's not so easy to just update it. Are you able to test it?

Best regards,
Thomas

**Comment by almereyda** [comment]
Which of the additional features from the 2.x series would you need supported in this CSI driver, in case they are not automatically activated and in use by syntactic compatibility of the `zpool` and `zfs` commands? I.e., if not specified, the new Zstd compression should be in use automatically.

From https://github.com/openzfs/zfs/releases I can see, that e.g. the InfluxDB support of the 2.1 release, but from skimming that page I don't seem to find breaking changes.

**Comment by t3hmrman** [comment]
Just want to note that `zfs-localpv` does work with ZFS 2.x -- I'm running v2.1.1-1:

```console
# zfs version
zfs-2.1.1-1
zfs-kmod-2.1.1-1
```

`zstd` can't be specified as a `compression` setting but it can indeed by used by default (assuming your pool is set up correctly and you don't specify `compression` on the storage class). I've confirmed:

```console
# zfs get compression tank/pvc-82298caf-3bca-4521-830e-768b8170d3b8
NAME                                           PROPERTY     VALUE           SOURCE
tank/pvc-82298caf-3bca-4521-830e-768b8170d3b8  compression  zstd            inherited from tank
```

As far as workloads I've run `fio` and `pgbench`with no problems (and of course other actual databases and apps) -- I haven't run into any issues yet!

**Comment by pawanpraka1** [comment]
thanks @t3hmrman for confirming this. I will add support for zstd compression. We just need to update the validation list and add zstd also in the list.
