### ISSUE TITLE
Missing zfsnode-crd.yaml in kustomization.yaml resources

### ISSUE THREAD

**Issue by sbidoul** [openebs/zfs-localpv#364]
**What steps did you take and what happened:**

When installing using kustomize as mentioned in the readme, the `zfsnodes.zfs.openebs.io` crd is not created.

**What did you expect to happen:**

`kubectl apply -k deploy/yamls` should install all necessary resources, similar to what `kubectl apply -f deploy/zfs-operator.yaml` does.

**Comment by pawanpraka1** [comment]
@sbidoul zfsnode CRD is already there in the deploy yamls https://github.com/openebs/zfs-localpv/tree/master/deploy/yamls.

**Comment by sbidoul** [comment]
Yes but it is missing in [kustomization.yaml](https://github.com/openebs/zfs-localpv/blob/c0653530bd457030f1e4079d2f1730548150c44a/deploy/yamls/kustomization.yaml#L4).

**Comment by pawanpraka1** [comment]
@sbidoul right. Would you like to raise a PR to fix that?

**Comment by sbidoul** [comment]
I can do that. Which should be the target branch (master or 1.9.x) ?

**Comment by pawanpraka1** [comment]
It is the master branch.
