### ISSUE TITLE
filesystems not removed after zpool was offline

### ISSUE THREAD

**Issue by skoef** [openebs/zfs-localpv#398]
**What steps did you take and what happened:**
A machine of ours that is running the zfs-localpv driver recently had an issue with the zpool that took some time to investigate. In the meantime, no productions pods were scheduled on this machine, but it was online. An operator running in the cluster regularly creates and removes snapshots and kept doing so during the outage.

Creating new snapshots obviously failed and the driver kept trying to ensure this for as long as the outage took. The cleaning of the snapshots however succeeded in the perspective of the driver:

```
I1108 15:08:55.087960       1 zfs_util.go:683] deleted snapshot pvc-24bf1c9a-5858-4e81-be77-822d42bcbc55@snapshot-16b1d680-57b1-4b70-8e96-d69c755e14b7
E1108 15:08:55.103201       1 zfs_util.go:667] destroy: snapshot pvc-24bf1c9a-5858-4e81-be77-822d42bcbc55 is not present, error: exit status 1
```
While this looks like and is logged like an error is in fact the expected result: the driver must ensure the snapshot is no longer there and it isn't. Job done!

**What did you expect to happen:**

In our case, as soon as the zpool came online again, there was a huge difference between the volumesnapshots in kubernetes and the ZFS snapshots on disk. The desirable situation would be that the driver would detect not only the ZFS snapshot was not there but also the rest of the zpool and therefor considered the snapshot not deleted (yet).

**Anything else you would like to add:**
While fetching the version our ZFS-LocalPV deployment I saw there has been a lot of releases in between, so I'll investigate upgrading my setup anyway.

**Environment:**
- ZFS-LocalPV version: 1.3.0
- Kubernetes version (use `kubectl version`): 1.18.9
- Kubernetes installer & version: manual
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by pawanpraka1** [comment]
> The desirable situation would be that the driver would detect not only the ZFS snapshot was not there but also the rest of the zpool and therefor considered the snapshot not deleted

@skoef was the pool offline when the snapshot was deleted by the operator? The driver expects that pool is always online and it goes ahead and checks that snapshot is present or not, if snpashot is not present, the driver will throw this error `destroy: snapshot pvc-24bf1c9a-5858-4e81-be77-822d42bcbc55 is not present` and will go ahead the clean up the ZFSSnapshot object.

**Comment by skoef** [comment]
That's exactly the point @pawanpraka1, the driver can't tell the difference between this particular ZFS snapshot being in fact already deleted or the entire zpool is not imported at that point. So the ZFSSnapshot objects get deleted leaving the actual ZFS snapshots dangling as soon as the pool comes online again.

**Comment by pawanpraka1** [comment]
@skoef This is a new feature request, I will add this to our road map.

**Comment by skoef** [comment]
thanks a lot @pawanpraka1!
