### ISSUE TITLE
@ptthon you need zfs 0.8 or higher version to have encryption. It will not work on zfs 0.7.

### ISSUE THREAD

**Issue by ptthon** [openebs/zfs-localpv#411]
@ptthon you need zfs 0.8 or higher version to have encryption. It will not work on zfs 0.7.

_Originally posted by @pawanpraka1 in https://github.com/openebs/zfs-localpv/issues/410#issuecomment-1119527782_

I have update zfs,now zfs version is:
zfs-2.1.2-1
zfs-kmod-2.1.2-1

but create encrypted volume failed

openebs-zfs-node log is:
I0510 06:33:50.454231       1 volume.go:123] Got add event for ZV zfspv-pool/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a
E0510 06:33:50.486544       1 zfs_util.go:424] zfs: could not create volume zfspv-pool/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a cmd [create -o quota=1073741824 -o encryption=on -o keylocation=file:///home/keys/key -o keyformat=raw -o mountpoint=legacy zfspv-pool/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a] error: cannot create 'zfspv-pool/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a': invalid property 'encryption'
I0510 06:33:50.500245       1 volume.go:254] Successfully synced 'openebs/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a'
I0510 06:33:51.485794       1 volume.go:144] Got update event for ZV zfspv-pool/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a
E0510 06:33:51.502932       1 zfs_util.go:635] destroy: volume zfspv-pool/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a is not present, error: exit status 1
I0510 06:33:51.517054       1 volume.go:169] Got delete event for ZV zfspv-pool/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a
E0510 06:33:51.520662       1 volume.go:259] error syncing 'openebs/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a': Operation cannot be fulfilled on zfsvolumes.zfs.openebs.io "pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a": StorageError: invalid object, Code: 4, Key: /registry/zfs.openebs.io/zfsvolumes/openebs/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: aab7ea05-dda1-4888-b99d-46a0404ac2db, UID in object meta: , requeuing
E0510 06:33:51.520715       1 volume.go:50] zfsvolume 'openebs/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a' has been deleted
I0510 06:33:51.522293       1 volume.go:254] Successfully synced 'openebs/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a'
E0510 06:33:51.525826       1 volume.go:50] zfsvolume 'openebs/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a' has been deleted
I0510 06:33:51.526099       1 volume.go:254] Successfully synced 'openebs/pvc-ee2d7019-e7ba-468c-b80d-e435e7f2f73a'

**Comment by pawanpraka1** [comment]
@ptthon can you manually try to create encrypted volume on the node? Also please make sure all the nodes are upgraded to zfs 2.1.2.

**Comment by ptthon** [comment]
> @ptthon can you manually try to create encrypted volume on the node? Also please make sure all the nodes are upgraded to zfs 2.1.2.

I can manually  create encrypted volume on the node,but only one node zfs version is 2.12,I will try all nodes ZFS upgrade to 2.1.2

**Comment by pawanpraka1** [comment]
yes, please upgrade all the nodes.

**Comment by sinhaashish** [comment]
answered
