### ISSUE TITLE
[bug] failed to parse volsize

### ISSUE THREAD

**Issue by TheRealNoob** [openebs/zfs-localpv#412]
**What steps did you take and what happened:**
When trying to expand a PVC we get an error `failed to parse volsize in for prometheus-0, {strconv.ParseInt: parsing "300Gi": invalid syntax}`.  We also tried `300Gb` and `300G`.  The PVC in question being for prometheus from the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) helm chart.

We eventually got it working by scaling down prometheus and changing the size in the `ZFSVolume` to be in bytes, then starting prometheus again with `300Gi` so it didn't trigger the resize.  The logs show a little larger because of some tinkering.  This is the only PV we've run into this issue with so far.  We did `zfs send recv` it from another machine a few weeks ago so not ruling out a user issue, but not sure what we could have done that would lead to this msg from the csi-resizer.
```
Warning  VolumeResizeFailed          1s (x5 over 6s)    external-resizer zfs.csi.openebs.io  resize volume "prometheus-0" by resizer "zfs.csi.openebs.io" failed: rpc error: code = Internal desc = ControllerExpandVolumeRequest: failed to parse volsize in for prometheus-0, {strconv.ParseInt: parsing "300Gi": invalid syntax}
```

**What did you expect to happen:**
PV to expand - `zfs set quota ...` on the node

**The output of the following commands will help us better understand what's going on**:

https://gist.github.com/TheRealNoob/724eca96276dcdfd03dcf6fe99030e0c

**Anything else you would like to add:**

I noticed that the Status on the ZFSVolume is blank `status: {}` which is different from the rest of our volumes which are Ready.  Even though the PVC is bound and we're back up and running at 300Gi.

Additionally I noticed that there is new releases of the [csi-resizer](https://github.com/kubernetes-csi/external-resizer/releases).  Any reason the latest version isn't the default on the chart?  Our k8s version meets the minimum requirement for both, but only 1.3 for the recommended version (our CNI lags a little behind).

**Environment:**
- kubernetes version `1.22.8`
- OS `Ubuntu 20.04.4 LTS`
- ZFS version `zfs-0.8.3-1ubuntu12.13   zfs-kmod-0.8.3-1ubuntu12.13`
- helm chart `zfs-localpv-2.1.0`

below all defaults from chart
- csi-resizer:  `k8s.gcr.io/sig-storage/csi-resizer:v1.2.0`
- csi-provisioner:  `k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0`
- openebs-zfs-plugin:  `openebs/zfs-driver:2.1.0`

**Comment by pawanpraka1** [comment]
> We eventually got it working by scaling down prometheus and changing the size in the ZFSVolume to be in bytes

@TheRealNoob how did you get the ZFSVolume size in Gi? Did you create the CR manually? ZFSVolume CR gets create the ZFS-LocalPV driver and it should be in bytes only.

**Comment by TheRealNoob** [comment]
You're correct.  Sorry for the false report.  Closing issue.  On a side note, I have been looking for a section that highlights documentation to this extent.  Is there such a page you may know of?
