### ISSUE TITLE
sigs versions and crds

### ISSUE THREAD

**Issue by jr0dd** [openebs/zfs-localpv#417]
**Describe the problem/challenge you have**

I noticed that the sigs deps are a little behind in the chart. The snapshotter for example is currently at 6.0.1 while the chart is still on 4.0.0. Not a huge deal when it comes to image tags in the chart because that can simply be changed. The issue is that you also include the crds for the snapshotter. Issues may arise from using the older crd's included when using newer images. Sigs updates their crd's pretty frequently.

**Describe the solution you'd like**

It would be ideal to keep these updated in the chart or maybe pull them from their [repo](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd) when

```
crd:
    enableInstall: true
```

**Comment by Abhinandan-Purkait** [comment]
@jr0dd We have updated the sigs deps. We have also added https://github.com/openebs/zfs-localpv/blob/1b0b77eb15cd895ba2a74e572dd0f5e6e409c693/deploy/helm/charts/values.yaml#L174 to handle the crds on install. Thanks
