### ISSUE TITLE
Non-privileged container

### ISSUE THREAD

**Issue by jackmurray** [openebs/zfs-localpv#424]
Having had a quick look over the manifest yaml, it looks like the operator container runs in privileged mode. Are there any plans to support running without this, and instead allow running as a restricted user (with permissions granted via `zfs allow`)? As it stands it seems like a huge security risk to run as essentially root.

**Comment by sinhaashish** [comment]
We will try this out using the non privileged mode and update here

**Comment by Abhinandan-Purkait** [comment]
Scoping the investigation for v4.2.

**Comment by sinhaashish** [comment]
Upon investigation I found that `zfs allow` doesn't support `mount`, `unmount` which are needed for node agent 
Refer [here ](https://openzfs.github.io/openzfs-docs/man/master/8/zfs-allow.8.html#DESCRIPTION).
Thus this request can not be done so closing this for now.
