### ISSUE TITLE
in kubevirt, cannot be resize in running vm

### ISSUE THREAD

**Issue by garweyYeh** [openebs/zfs-localpv#425]
![image](https://user-images.githubusercontent.com/44438145/190989636-e8f2c2d9-1fa1-43bc-9e7e-8da214b872f5.png)

**Comment by Icedroid** [comment]
I meet the same problem. We can't resize for block pvc as follow:
https://bytemeta.vip/repo/openebs/zfs-localpv/issues/280?page=2

**Comment by pawanpraka1** [comment]
@Icedroid that issue (https://github.com/openebs/zfs-localpv/issues/280) is fixed. The error mentioned in this issue is not coming from the ZFS-LocalPV driver. This seems like kubelet is throwing that error. Can you check if there is anything wrong from cluster setup side?

**Comment by sinhaashish** [comment]
@Icedroid this issue is stale since there is no reply from your side. Please feel free to raise another issue if you face the problem, thanks.
