### ISSUE TITLE
missing zvol (that exists in "zfs list")

### ISSUE THREAD

**Issue by privatecoder** [openebs/zfs-localpv#428]
**What steps did you take and what happened:**

Volume created through StorageClass

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/45964815/203341559-a762ee49-1deb-4559-8c01-8b96d4bd1f34.png">

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/45964815/203341658-b8e4a268-2172-4682-bd35-42365dddf074.png">

on the node via `zfs list`:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/45964815/203340839-5a3a39da-17fb-424e-a788-7c00148db6cf.png">

but missing in `/dev/zvol/zfspv-encrypted-pool`

<img width="768" alt="image" src="https://user-images.githubusercontent.com/45964815/203340901-8c4b833a-b842-49da-b04e-53db99b0a577.png">

Found this bug-report here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=262189

Rebooting does fix this, as the missing zvol exists afterwards.

**What did you expect to happen:**

zvol should always be created

**Anything else you would like to add:**

tested both, vendor:

```
zfs-0.8.3-1ubuntu12.14
zfs-kmod-2.0.6-1ubuntu2.1
```

and PPA version:

```
zfs-2.1.6-0york1~20.04
zfs-kmod-2.0.6-1ubuntu2.1
```

**Environment:**
- ZFS-LocalPV version: v2.1.0
- Kubernetes version: v1.24.8
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 HWE (tried both, zfs that ships with it and PPA )

**Comment by privatecoder** [comment]
changing `volmode=default` (which defaults to `full`/`geom`) to `volmode=dev` for the pool fixes the issue.

**Comment by sinhaashish** [comment]
@Privatecoder  , thanks for your update. Please feel free to raise any new issue if you face any problem in future
Closing this issue for now
