### ISSUE TITLE
enable fstype xfs type gp3

### ISSUE THREAD

**Issue by sunilemanjee** [openebs/zfs-localpv#431]
[A description of the current limitation/problem/challenge that you are experiencing.]
Using openebs hostpath option on AWS EKS, it automatically defaults to using gp2.  

**Describe the solution you'd like**
Enable option to use gp3

**Anything else you would like to add:**
If there is currently a way to do this, the docs don't seem to be clear about it.  Any guidance appreciated. 

**Environment:**
- ZFS-LocalPV version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by sinhaashish** [comment]
hi @sunilemanjee  
Can you please confirm whether you are talking about `openebs hostpath` or `ZFS-LocalPV` as your comment section says `openebs hostpath` while the environment section  says `ZFS-LocalPV`.

Moreover we are happy to accept any PR from your side for this issue

**Comment by sunileman** [comment]
I opened this jan 30th. I have found a alternate solution. The docs for openebs provide zero guidance on using gp3.

**Comment by sinhaashish** [comment]
@sunileman Thanks for sharing the update . Can you also please share the alternate solution, it will be helpful for the community .

**Comment by sinhaashish** [comment]
closing this as there is no response.
