### ISSUE TITLE
k8s.gcr.io image registry freeze

### ISSUE THREAD

**Issue by Da-Juan** [openebs/zfs-localpv#435]
Hello

**Describe the problem/challenge you have**
On the 3rd of April 2023, the old registry `k8s.gcr.io` will be frozen and no further images for Kubernetes and related subprojects will be pushed to the old registry. ([source](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/)).

**Describe the solution you'd like**
Could you please update the deployment manifests to use the "new" registry `registry.k8s.io`?
Thanks!

**Comment by vharsh** [comment]
Closing this as it seems to be fixed.

cc @niladrih
