### ISSUE TITLE
Support setting compression to zstd-{1-19}

### ISSUE THREAD

**Issue by jnels124** [openebs/zfs-localpv#438]
**Describe the problem/challenge you have**
Currently, the CRD for a zv doesn't allow compression to be set to zstd variants. ie zstd-6.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Update the regex to allow zstd variants to be set

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- ZFS-LocalPV version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by sinhaashish** [comment]
Closing the issue as the resolution to this issue is merged in #461 . 
There was also another PR #439 raised for this , which has been closed as the relevant code changes were present in PR #461.
