### ISSUE TITLE
Is this project still actively maintained ? 

### ISSUE THREAD

**Issue by rdegez** [openebs/zfs-localpv#442]
Last commit on the develop branch is from Jul 14, 2022 so it makes me wonder what is the current status of the project.
Looks like the OpenEBS acquisition by DataCore wasn't a very good news for various OpenEBS projects...
Nevertheless, this project is still very useful and I don't know of any other CSI implementing zfs local volume on-par with it feature wise.
So... should we fork it or will someone from the current projet team show up and gives us some insight on what's going on ? :-)

**Comment by lcaflc** [comment]
Same question here.

This project is awesome and by far the best local storage provisioner. We really love ZFS and it work just fine.
But with the changes happening in CSI drivers in k8s, will the project be able to keep up with those ?

**Comment by dalbani** [comment]
I'm also a very satisfied user of this provisioner. I hope a solution can be found to have it back actively maintained.

**Comment by avishnu** [comment]
We acknowledge your concerns. Please wait for a communication regarding the same in the next few days. Meanwhile, you are welcome to raise PRs here.

**Comment by rdegez** [comment]
Great, thanks!

**Comment by RachelAmbler** [comment]
Two weeks later....?

**Comment by avishnu** [comment]
We will continue to maintain the OpenEBS ZFS LocalPV driver. The changes will be primarily around, but not limited to, security fixes, API schema updates, Golang version updates and CSI updates. As the project is quite mature w.r.t. the feature list, the focus won't be on major enhancements.
Community contributions are always welcome.

The latest release of OpenEBS includes changes to this driver as well: https://github.com/openebs/openebs/releases/tag/v3.7.0

**Comment by dalbani** [comment]
That's very good nieuws to hear that ZFS LocalPV will be maintained. Thanks!

**Comment by hrudaya21** [comment]
This project is actively getting checked. If any problem faced in this repo, new issue can be raised in github. We are open to new PRs to this repo.
