### ISSUE TITLE
Volume should not be provisioned on the nodes like master node which are marked as noScheduled

### ISSUE THREAD

**Issue by w3aman** [openebs/zfs-localpv#47]
**what happened:**
- zpool was created on all of the worker nodes where application pods can be scheduled.
- When volume was provisioned PV  scheduling was created on master node which in general marked as a noSchedule node. Because of that PV which is created on master node, application pod remains in Pending state as it doesn't get volume.
- FYI in storage class spec under allowedTopologies field list of nodes, where zpool is present, was intentionally not used as all the worker node are having zpools.

**what you expected to happen**
- PV should not be created on master nodes. For that zfs provisioner should be aware of such info like NoScheduling.

**Comment by pawanpraka1** [comment]
@freym sorry for the delay. There are two things probably we can (after discussing it internally and with CSI community)
1. Change the key from 'kubernetes.io/hostname" to some unique name which is not present on the node. Since this label is already present on the master node, so because of that this is being considered and the driver is scheduling the PV on that node. We will change the key to "openebs.io/nodename". So now we don't have to list the worker node in case master in not schedulable. In this case we have to update the storageclass and change the key to "openebs.io/nodename".
2. Second thing, to support the buildings/zpool_type, here we can label the nodes whatever way we want and we can mention that in the storageclass, for this to work, we have to change our scheduler to expect any key rather that the supported keys only. WaitForFirstConsumer will not work here as topology key spefified in the storageclass is not supported by the driver, this limitation comes from the CSI provisioner itself.

**Comment by pawanpraka1** [comment]
@freym I have raised the PR(https://github.com/openebs/zfs-localpv/pull/94) to support custom keys. We can now label the nodes and then deploy the ZFS-LocalPV driver. The driver will support all the keys that node has.

**Comment by pawanpraka1** [comment]
@freym The PR to support custom topology has been merged. You can follow the steps mentioned here to add custom topology key : https://github.com/openebs/zfs-localpv/blob/master/docs/faq.md#6-how-to-add-custom-topology-key.
Let us know if you are facing any issue.

@w3aman We have fixed the issue(via https://github.com/openebs/zfs-localpv/pull/101) where we have to list all the worker nodes in the storageclass to make ZFS-LocalPV driver not to create any PV on the master node. Can you please try out and see if that is working?

**Comment by w3aman** [comment]
Cool...i will try this out !
Thanks @pawanpraka1 for your work on this issue.

**Comment by w3aman** [comment]
I tried this scenario with both v0.6.x and ci image. Both the time i kept master node with NoSchedule taint. And in PVC spec i used immediate as volume binding mode. ci images solved this issue, as master was on noSchedule taint it didn't provisioned the volume there.

with v0.6.x:
```s@e2e2-dev-master:~$ kubectl get zv -n openebs
NAME                                       ZPOOL   NODE              SIZE         VOLBLOCKSIZE   RECORDSIZE   FILESYSTEM   CREATIONTIME   AGE
pvc-17d977c6-3b89-4fe8-a1ba-0b0273bd0ee3   test    e2e2-dev-master   1073741824                  4k           zfs                         2m46s
pvc-bdd37896-fd1b-40ce-a614-6b83c9b41403   test    e2e2-dev-node3    1073741824                  4k           zfs                         76s
pvc-ca27fe42-90d4-430a-8301-8bd0c6031d7f   test    e2e2-dev-node1    1073741824                  4k           zfs                         44s
pvc-d9be6f4c-c6ce-4b4b-8f59-76599d4febfb   test    e2e2-dev-master   1073741824                  4k           zfs                         14s
pvc-f57ad11a-65cb-4558-aa1f-c3c9c6f39a02   test    e2e2-dev-node2    1073741824                  4k           zfs                         58s
```

But with CI images volumes were provisioning on the worker nodes only. 
```
devuser@rack2:~/aman$ kubectl get zv -n openebs
NAME                                       ZPOOL   NODE        SIZE         VOLBLOCKSIZE   RECORDSIZE   FILESYSTEM   CREATIONTIME   AGE
pvc-1f729f0d-5d01-4dff-86d9-2b4fd9dc7fbc   test    k8s-node2   1073741824                  4k           zfs                         37m
pvc-3253a2c8-ce54-4a75-a029-9d610186eeaf   test    k8s-node3   1073741824                  4k           zfs                         37m
pvc-6814a63b-d566-4e1d-b1f4-cf8913ec21a9   test    k8s-node1   1073741824                  4k           zfs                         36m
pvc-cd62da32-0c4f-4b1d-945b-cad001da4bac   test    k8s-node1   1073741824                  4k           zfs                         38m
```
**Note:** Here, because of zfs-schedular volume-count based scheduling is done. so in (1 master + 3 worker) cluster provisioning of 4 volumes should consider all 4 nodes one by one but because of the taints, master was not the suitable candidate for provisioning volume so the 4th one goes with node-1 again.
