### ISSUE TITLE
K8s required ports need to be manually enabled after zfs-localpv installation

### ISSUE THREAD

**Issue by mohammadkarami2023** [openebs/zfs-localpv#476]
I installed zfs-localpv on my k8s cluster and after the installation I could not access to my running pods using kubectl exec receiving
Error from server: error dialing backend: dial tcp 172.16.10.110:10250 errors.
I had cilium(1.14.1) cni and using "kubectl describe" i realized that it sends healthz warning. I changed my CNI to weave(2.8.1) and the warning gone but still i was unable to to access my pods. Finally i realized that i need to enable ports mentioned : [https://stackoverflow.com/questions/60207682/how-do-i-add-firewall-rules-to-allow-nodeports-accessed-over-virtual-ip-in-kuber](url) to handle that

Still, cilium does not works but using weave everything works. How zfs-localpv disables the necessary ports and how to avoid that?

**Environment:**
- ZFS-LocalPV version: zfs-localpv-2.3.1
- Kubernetes version (use `kubectl version`): 1.28.1
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

**Comment by hrudaya21** [comment]
@mohammadkarami2023 If the firewall is enabled in your env, then default kubernetes port needs to be bypass as per the link provided by you. This is not controlled by zfs-localpv code.

**Comment by Abhinandan-Purkait** [comment]
@mohammadkarami2023 This seems to fall under k8s cluster configuration and is an out of scope item for zfs. Closing this, please feel free to reopen if you feel otherwise.
