### ISSUE TITLE
ZFS Controller leader election arguments in helm charts

### ISSUE THREAD

**Issue by trunet** [openebs/zfs-localpv#486]
**Describe the problem/challenge you have**

I would like to contribute back to this project, but first would like to discuss how. It's simple, but it would help me.

I'm running zfs-localpv on a "cheap" homelab. It's 3 x mini-pcs with i3 and it have lots of tenants, way more than I would like, making my cluster being a little bit unresponsive at times.

I noticed that I'm having a large number of restarts on openebs-zfs-localpv-controller containers:

```
    Image:         registry.k8s.io/sig-storage/csi-resizer:v1.8.0
    Restart Count:  11
    Image:         registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
    Restart Count:  9
    Image:         registry.k8s.io/sig-storage/snapshot-controller:v6.2.2
    Restart Count:  9
    Image:         registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
    Restart Count:  10
    Image:         openebs/zfs-driver:2.3.0
    Restart Count:  0
```

Due to leader election:

```
...
I1107 11:30:33.053211       1 leaderelection.go:276] successfully renewed lease openebs/zfs-csi-openebs-io
E1107 11:30:48.056150       1 leaderelection.go:364] Failed to update lock: Put "https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/openebs/leases/zfs-csi-openebs-io": context deadline exceeded
I1107 11:30:48.056214       1 leaderelection.go:280] failed to renew lease openebs/zfs-csi-openebs-io: timed out waiting for the condition
F1107 11:30:48.056269       1 leader_election.go:182] stopped leading
```

I saw on the helm charts that `zfsController.replicas` is not listed on the documentation, but available on values,yaml, defaulting to 1. `--leader-election` argument is required only when replicas is higher than 1 according to [external-resizer](https://github.com/kubernetes-csi/external-resizer#recommended-optional-arguments) documentation.

**Describe the solution you'd like**

I thought about adding `extraArguments` on each zfsController container variable where we can fine tune election deadline/duration/period to reduce its load.

Each `extraArguments` would default to `[--leader-election]` to keep backward compatibility but anyone would be free to just set it an empty list.

**Anything else you would like to add:**

I have a local fork being used. I can send a PR once you agree with the proposal. Don't want to waste my time with something that will not be accepted/merged.

**Environment:**
- ZFS-LocalPV version: 2.3.1
- Kubernetes version (use `kubectl version`): v1.29.0-alpha.3
- Kubernetes installer & version: Talos
- Cloud provider or hardware configuration: Talos
- OS (e.g. from `/etc/os-release`): Talos v1.6.0.alpha.1

**Comment by pawanpraka1** [comment]
@trunet, Proposal looks good. Please go ahead with the implementation.

**Comment by trunet** [comment]
Submitted PR, please review it.
