### ISSUE TITLE
GetNodeID failed for node

### ISSUE THREAD

**Issue by aep** [openebs/zfs-localpv#493]
when adding a node to  StorageClass.allowedTopologies  , nothing appears to create the matching zfsnode.zfs.openebs.io

the openebs-zfs-node pod is started but crashes with

```
F1204 13:06:11.157906       1 volume.go:92] GetNodeID failed for node=uca3k err: failed to get the node uca3k
```

in testing, this recovers when deleting all pvc and storageclass.

**Comment by sinhaashish** [comment]
Can you please check PR #451 . It has the way how to set the labels for node.

**Comment by aasseman** [comment]
I built v2.4.1 myself (because of #503). It does **not** fix this issue.

**Comment by aasseman** [comment]
I can't recover from this. I tried removing everything (storageclasses, pvc, openebs itself). Rolling back all the way to version 2.2.0, I get the same error every time...
It seems that the problem is with https://github.com/openebs/lib-csi/blob/398853242f9da5b81ba0985bada51f4c015738b6/pkg/client/k8s/node.go#L74.

**Comment by aep** [comment]
closing because i never reproduced it

**Comment by aep** [comment]
reopening since it re-appeared when adding a node to an existing cluster.

i manually labeled the node as 

```
      openebs.io/nodeid: archive
      openebs.io/nodename: archive

```

but that did nothing

looking at the code i'm not even sure why that would be related

https://github.com/openebs/zfs-localpv/blob/763ff6de8cdc2fee68b6cb005d6aca1e93732ddd/pkg/zfs/volume.go#L105C22-L105C30

the error returned here is just eaten, so we cant see the cause

**Comment by avishnu** [comment]
@aep were you able to figure out the reason once your fix went in?

**Comment by aep** [comment]
Yes. Showing the actual error allowed me to find out it's a K8s API server issue. This can be closed.

**Comment by avishnu** [comment]
Glad to know it helped !!
Would you be kind enough to get added as an OpenEBS Adopter here? https://github.com/openebs/openebs/issues/2719
Thanks !!
