### ISSUE TITLE
velero plugin maintenance

### ISSUE THREAD

**Issue by aasseman** [openebs/zfs-localpv#511]
Is [openebs/velero-plugin ](https://github.com/openebs/velero-plugin) still maintained? I see it's been still for 2 years.

The main issue with this is that the docs are pointing to using velero for backups: https://github.com/openebs/zfs-localpv/blob/develop/docs/backup-restore.md. Perhaps retiring it officially would avoid new users struggling to make it work.

In particular I'm experiencing https://github.com/openebs/velero-plugin/issues/185, but I don't see the point in posting an issue there since nobody seems to be looking at it.

**Comment by ianb-mp** [comment]
I note that the OpenEBS [ROADMAP.md](https://github.com/openebs/openebs/blob/main/ROADMAP.md) shows [openebs/velero-plugin](https://github.com/openebs/velero-plugin) under heading "Repos to be DEPRECATED and ARCHIVED"

My understanding is that velero-plugin was originally built for the legacy cStor engine which is being deprecated. I would be a shame if it is not kept for zfs-localpv.

**Comment by Abhinandan-Purkait** [comment]
@ianb-mp The openebs/velero-plugin will be maintained only with the scope for zfs localpv. The cstor support would be removed going forward as cstor is deprecated. cc @avishnu @dave-brace

**Comment by Abhinandan-Purkait** [comment]
@aasseman @ianb-mp If there are no further questions, can we close this? Thanks

**Comment by aasseman** [comment]
@Abhinandan-Purkait feel free to close :+1:

**Comment by Abhinandan-Purkait** [comment]
Thanks
