### ISSUE TITLE
URGENT: Helm chart for 2.5.0 deletes VolumeSnapshot CRDs - including all snapshots

### ISSUE THREAD

**Issue by wolfgangwalther** [openebs/zfs-localpv#517]
**What steps did you take and what happened:**

I updated my helm chart to v2.5.0. Because of some broken logic, this caused the VolumeSnapshot, VolumeSnapshotClasses and VolumeSnapshotContents CRDs to be deleted - and with them **all the volume snapshots in the cluster**.

**What did you expect to happen:**

I expected by backups not to be deleted...

---

This line is the problem:

https://github.com/openebs/zfs-localpv/blob/46005580c5e35a671b858995f494116925c9d5a6/deploy/helm/charts/charts/crds/templates/csi-volume-snapshot.yaml#L3

This will cause the volume snapshot CRDs to not be rendered when they are already available in the cluster... which will then cause helm to remove the CRD. Helm will basically flip between installing and uninstalling the CRD on every update, because they are missing once and are present the next time...

Before #488 those were in the `crds` folder, which caused helm to treat them specially, I think - i.e. it would only install them, but not remove them. In this case the check probably made sense to avoid errors when they were already present.

Updating to v2.5.0 is seriously harmful. I wonder whether there is any way to retract that release. In any case, this should be fixed ASAP.

**Comment by wolfgangwalther** [comment]
One thing I don't understand, yet, is why the `zfs*` CRDs are not affected by that. They have the same logic, but are kept in place for me.

**Comment by tiagolobocastro** [comment]
Hi @wolfgangwalther, seems this is to do with the new CRD as a sub-chart method. We'll discuss with the team tomorrow on how to proceed.

**Comment by tiagolobocastro** [comment]
> fireddddd.

@Ornias1993 that's not a very cool remark tbh, mistakes happen, let's just move on and try to come up with a better way.

Now on the helpful part of the comment :)
The CRDs were removed from templates so we can't add the "resource-policy" to them.
Going forward should consider adding this to all of our CRDs?

**Comment by Abhinandan-Purkait** [comment]
> > that's not a very cool remark tbh
> 
> I think that's pretty-much off-set by the level of "not-cool" making this level of mistakes in charts that are, quite widely, used in production. Which is completely unacceptable.
> 
> > Now on the helpful part of the comment :) The CRDs were removed from templates so we can't add the "resource-policy" to them. Going forward should consider adding this to all of our CRDs?
> 
> No, you removed them from `/crds` and you move them _into_ `/templates` of a subchart: https://github.com/openebs/zfs-localpv/tree/develop/deploy/helm/charts/charts/crds/templates
> 
> Which is the whole reason why the templating quoted here worked in the first place. As `/crds` doesn't support templating _at all_

FYI the volume snapshot crds were a part of /templates dir in the first place. The things under /crds folder were zfs specific crds which were not removed in the upgrade process anyway. 
ref: https://github.com/openebs/zfs-localpv/tree/zfs-localpv-2.4.2/deploy/helm/charts/templates

The fact that VolumeSnapshot CRD would get removed even with CRs present wasn't on your checklist as these are operated by external-snapshotter and csi-snapshot-controller which are not our components, and it ideally should have been handled by them. It's unfortunate that it's not. We have removed the release for now to prevent it for the time being, so that we can come up with a way to handle this. 

@wolfgangwalther We would appologize for the trouble. Can you please get back to the previous release till we can have a upgrade path. Thanks.

**Comment by wolfgangwalther** [comment]
> We would appologize for the trouble. Can you please get back to the previous release till we can have a upgrade path. Thanks.

Yes, I already did yesterday. I just wanted to raise this with urgency here to make sure nobody else falls into the same trap. Retracting the release for now is surely the right decision.

Thanks for the quick reaction!

**Comment by wolfgangwalther** [comment]
> > that's not a very cool remark tbh

100% agree.

> I think that's pretty-much off-set by the level of "not-cool" making this level of mistakes in charts that are, quite widely, used in production. Which is completely unacceptable.

It's our decision to use this in production. This is Open Source. Of course, it's not cool, but you can hardly argue there was any intent here.

From my side a big thank you to those maintaining this project. I had been looking for a while for the same for btrfs, but ultimately made the switch to zfs and zfs-localpv - very happy with it.

**Comment by Abhinandan-Purkait** [comment]
@wolfgangwalther We have released 2.5.1 helm chart with the fix and it's safe to upgrade to this version. You would need to use `--set crds.zfsLocalPv.enabled=false` while doing the upgrade assuming you are have installed zfs from zfs chart and not the openebs umbrella chart. You don't need to change any other values. Once upgraded the volume snapshot crds will get patched with `helm.sh/resource-policy: keep` annotation.

NOTE: The crds would now come from a different dependency chart. Installation for this chart is enabled by default in for both install and upgrade. It is important that this chart be enabled.

**Comment by wolfgangwalther** [comment]
> We have released 2.5.1 helm chart with the fix and it's safe to upgrade to this version. You would need to use --set crds.zfsLocalPv.enabled=false while doing the upgrade assuming you are have installed zfs from zfs chart and not the openebs umbrella chart.

Thanks for the heads up!

I updated to v2.5.1 without this setting - and as expected the update fails, because the zfs CRDs already exist, but has "invalid ownership metadata". :+1:

I'd like to have this chart adopt the zfs CRDs from now on, so I patched the definitions manually to include `app.kubernetes.io/managed-by`, `meta.helm.sh/release-name` and `meta.helm.sh/release-namespace`.

The update succeeded, all CRDs have been adopted and patched with the keep-policy. Nice work!

**Comment by niladrih** [comment]
@wolfgangwalther Awesome! The move to the new installer caused quite a bit of friction. 

Completely unrelated, but I got myself an EVH Wolfgang Standard in December (sparkly gold :D).

I hope both of the Wolfgangs have an amazing year ahead. Thank you for working through this with us.

**Comment by edrob999** [comment]
@Ornias1993: I agree with everyone, recommending someone gets fired in an open source CNCF project forum is not cool. Same with the intern comment. We're trying to support each other and set a welcoming tone for everyone in the community.
