### ISSUE TITLE
Feature request: human-readeable names of volumes (with namespacing)

### ISSUE THREAD

**Issue by ghormoon** [openebs/zfs-localpv#520]
**Describe the problem/challenge you have**
I'm planning to use external backup solution for snapshots and zfs send/recv (most likely syncoid or znapzend).
I'd like to be able to see what PVC dataset belongs to even on my backup target that won't be running kubernetes.
Also it would allow for easier restore.

**Describe the solution you'd like**
It would be nice if there was a toggle, that would switch the behaviour from creating "pvc-uuid" named datasets/zvols to "namespace/pvc-name" (or at least "namespace-pvc-name"). This should be still unique, so the uuid is not necessary.
Additionally, i'd like to have a toggle that would allow to ignore conflicts - to be able to zfs recv a dataset and then create pvc, that would just map it into kubernetes, ingore any attempt at formatting it etc. (This can be also expanded by some options to zfs clone from another dataset, which would allow both the restoration to have eg VM templates, but that's much more complexity to add).

**Anything else you would like to add:**
I'm completely new to this but i'm willing to look into it later when i get more familiar with how it works in kube internally.

**Comment by Abhinandan-Purkait** [comment]
@ghormoon I believe this is same as an already existing issue. Please check and close this, and let's follow the other issue if its same. Thanks
https://github.com/openebs/zfs-localpv/issues/402

**Comment by ghormoon** [comment]
Closed in favor of #402
