### ISSUE TITLE
localpv-node hangs in CreateContainerError on talos

### ISSUE THREAD

**Issue by lazyIoad** [openebs/zfs-localpv#545]
**What steps did you take and what happened:**
 I'm running Talos Linux on a single node as both a control plane & worker node. I've been trying to set up Local PV ZFS following the [openebs guide](https://openebs.io/docs/user-guides/local-storage-user-guide/local-pv-zfs/zfs-configuration), and am stuck with the zfs pv node's `csi-node-driver-registrar` stuck with the repeated log `Still connecting to unix:///plugin/csi.sock`:
```shell
> kubectl get pods -n openebs
NAME                                             READY   STATUS                 RESTARTS       AGE
openebs-localpv-provisioner-7cd9f85f8f-hn4c2     1/1     Running                0              28m
openebs-zfs-localpv-controller-7fdcd7f65-mmd5g   5/5     Running                10 (32m ago)   128m
openebs-zfs-localpv-node-jsf79                   1/2     CreateContainerError   0              28m
```

I have a single ZFS pool `tank` with a single [storage class](https://gist.github.com/lazyIoad/4a7dfa8189e4dde6b13bff092cbea746).

I've also set the `openebs` namespace to be privileged:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
```

I'm also running the following extensions for Talos:
```
- siderolabs/iscsi-tools
- siderolabs/util-linux-tools
- siderolabs/zfs
```

I'm not entirely too sure how to go about debugging this, so any pointers would be helpful.

**What did you expect to happen:**
`openebs-zfs-localpv-node` should successfully start up

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

* `kubectl logs -f openebs-zfs-controller-f78f7467c-blr7q -n openebs -c openebs-zfs-plugin`: https://gist.github.com/lazyIoad/64ce40dc5cab08e66bc679599ce619bf
* `kubectl -n openebs logs -f openebs-zfs-localpv-node-jsf79 -c openebs-zfs-plugin`
```
Error from server (BadRequest): container "openebs-zfs-plugin" in pod "openebs-zfs-localpv-node-jsf79" is waiting to start: CreateContainerError
```
* `kubectl get pods -n openebs`
```
openebs-localpv-provisioner-7cd9f85f8f-hn4c2     1/1     Running                0              28m
openebs-zfs-localpv-controller-7fdcd7f65-mmd5g   5/5     Running                10 (32m ago)   128m
openebs-zfs-localpv-node-jsf79                   1/2     CreateContainerError   0              28m
```
* `kubectl get zv -A -o yaml`: nothing here

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LocalPV-ZFS version
- Kubernetes version (use `kubectl version`): `v1.30.1`
- Kubernetes installer & version: Talos
- Cloud provider or hardware configuration: Local bare-metal, running x86-64
- OS (e.g. from `/etc/os-release`): Talos 1.7.4

**Comment by lazyIoad** [comment]
Closing this out because I was able to figure out the issue. I realized that the driver was never installed:
```
kubectl get csinodes
NAME    DRIVERS   AGE
avion   0         4d6h
```

I checked `kubectl get events -n openebs` and saw:
```
4m2s        Warning   Failed                   pod/openebs-zfs-localpv-node-d9lnh                   Error: failed to generate container "e5c8cc2c1eae0616470fe06ef93d39c768c6204fc804542b13bb9f41905dc59d" spec: failed to generate spec: failed to mkdir "/home/keys": mkdir /home: read-only file system
```
which makes sense, given that /home is protected in Talos. I found https://github.com/openebs/zfs-localpv/pull/487 and was able to set `zfs-localpv.zfsNode.encrKeysDir` to a more suitable path, and now everything works as expected.

**Comment by zystem** [comment]
This solution helps me a lot. But it is not fully clear. The exact command to fix this error is
```
helm install openebs --namespace openebs openebs/openebs --set zfs-localpv.zfsNode.encrKeysDir=/var/openebs/keys --create-namespace
```
You can use any directory under /var

**Comment by tiagolobocastro** [comment]
I wonder if we should default to something in `/var`?
Also, do we need to document this @Abhinandan-Purkait ?

**Comment by Abhinandan-Purkait** [comment]
> I wonder if we should default to something in `/var`? Also, do we need to document this [@Abhinandan-Purkait](https://github.com/Abhinandan-Purkait) ?

Yeah we can do that probably, but that might break previous installs, if someone is using default. We can probably document this somewhere. Maybe in FAQ?
