### ISSUE TITLE
CI - zfs localpv ci needs improvement

### ISSUE THREAD

**Issue by Abhinandan-Purkait** [openebs/zfs-localpv#558]
**Describe the problem/challenge you have**
- Currently the charts live on develop. 
- We don’t have chart to use unless we bump helm chart version. This make it difficult for testing.
- We don’t have a reliable way of testing the helm charts.
- We don’t have develop equivalent chart for the engines. Which is needed for testing.

**Comment by Abhinandan-Purkait** [comment]
We have broken this down in several use cases. These would be worked upon use-case wise.

- [x] - When a PR is raised with base branch as develop -> #557 
- [x] - When a PR is raised with base branch as release/x.y -> #557 
- [x] - When a release/x.y branch is created
- [x] - When a PR is merged to develop branch
- [x] - When a PR is merged to release/x.y branch
- [x] - When a release tag is created from release/x.y branch

**Comment by avishnu** [comment]
@Abhinandan-Purkait can we mark this as completed?

**Comment by Abhinandan-Purkait** [comment]
@avishnu Yes, this can be marked as completed now. Closing this.
