### ISSUE TITLE
ZFS Reservation is not updated when resizing a volume (thinprovisining disabled).

### ISSUE THREAD

**Issue by donch** [openebs/zfs-localpv#568]
**What steps did you take and what happened:**

I've encountered an issue with volume expansion when using a StorageClass configured with `thinprovision=no`. While the initial volume creation correctly sets both the Quota and Reservation parameters for the ZFS volume, subsequent volume expansions only update the Quota, leaving the Reservation unchanged.

Here is an extended volume from 1Gi to 5Gi : 

```# zfs list -o name,quota,reservation,refquota,refreservation,used,avail
NAME                                              QUOTA  RESERV  REFQUOTA  REFRESERV   USED  AVAIL
zfspool                                            none    none      none       none  1.00G  29.5G
zfspool/pvc-b3b2e70d-a724-4a99-ad4a-bade4904e6da     5G      1G      none       none    25K  5.00G
```

**What did you expect to happen:**

Both ZFS Quota and Reservation should be updated during volume expansion to maintain consistency with the `thinprovision=no` setting.

Steps to reproduce:
1. Create a StorageClass with `thinprovision=no`
2. Create a PersistentVolumeClaim using this StorageClass
3. Verify initial Quota and Reservation values on the ZFS volume
4. Expand the PersistentVolumeClaim
5. Check Quota and Reservation values - only Quota will have been updated

**Anything else you would like to add:**

Any assistance in addressing this issue would be greatly appreciated, as it's critical for maintaining the expected behavior of non-thin-provisioned volumes in our environment.

**Environment:**
- LocalPV-ZFS version: chart openebs-4.1.0
- Kubernetes version (use `kubectl version`): v1.27.10+k0s 
- Cloud provider or hardware configuration: Proxmox VM
- OS (e.g. from `/etc/os-release`): Flatcar Container Linux by Kinvolk 3510.2.6

**Comment by Abhinandan-Purkait** [comment]
@donch Yeah, seems like it needs to be set from here, but it's not currently.
https://github.com/openebs/zfs-localpv/blob/d4c190358c4a10f859048ded9b65f0121357c52c/pkg/zfs/zfs_util.go#L295

Would be interested in taking this up?

**Comment by donch** [comment]
hi @Abhinandan-Purkait , I'm not very comfortable coding in Golang 😅 , could this potentially be addressed from your side?

**Comment by Abhinandan-Purkait** [comment]
@donch, sure, btw I am already occupied with the overhaul of the CI because there seems to be some gaps there. So it might take a while.

**Comment by Jonathan-Eid** [comment]
+1 this issue, very critical to get it working for my usecase
