### ISSUE TITLE
Chart zfs-localpv-controller antiAffinity rule

### ISSUE THREAD

**Issue by pando85** [openebs/zfs-localpv#590]
**What steps did you take and what happened:**
I'm running chart version 2.6.1 and there is an antiAffinity rule in the zfs-controller. I sawed that it was removing in 3a4d841cbb85d4d7404b724ac58465c7bc4018e9 on July but it triggers to us after upgrading to 2.6.1.

**Comment by Abhinandan-Purkait** [comment]
Hey @pando85 Thanks for pointing this out. We are in the middle of transition to a complete new CI for chart releasing and image publishing, as the older way had a lot of flaws. The helm chart lived on develop and not on release branches. That caused the new CI to miss out the changes on the branch from which the new chart was published. We have manually cherry-picked it now to fix it. From going forward we would not have to do this, the new CI should allow charts to live on their release branches. We will cut out a new 2.6.2 with the chart changes. That should resolve this issue.

**Comment by pando85** [comment]
Thanks for your fast answer and fix. I'm closing the issue.
