### ISSUE TITLE
RBAC permissions issue with patching volumesnapshotcontents/status

### ISSUE THREAD

**Issue by d4rkfella** [openebs/zfs-localpv#602]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.]
Hello, i was just troubleshooting why volumesnapshots werent working on my clusters and noticed the following issue. In the logs of csi-snapshotter container i saw this error ```I1205 17:20:28.918148       1 event.go:377] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"snapcontent-e267490f-5bb7-49b6-85bf-3bbc75d177a7", UID:"5a4c5d44-bded-40ae-b11c-d9ba480e53de", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"11056128", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: error updating status for volume snapshot content snapcontent-e267490f-5bb7-49b6-85bf-3bbc75d177a7: snapshot controller failed to update snapcontent-e267490f-5bb7-49b6-85bf-3bbc75d177a7 on API server: volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-e267490f-5bb7-49b6-85bf-3bbc75d177a7" is forbidden: User "system:serviceaccount:kube-system:openebs-zfs-controller-sa" cannot patch resource "volumesnapshotcontents/status" in API group "snapshot.storage.k8s.io" at the cluster scope``` 

After manually creating a clusterrolebinding to allow patching the status of volumesnapshotcontents, the issue went away and now im able to create volumesnapshots and csi-snapshotter is able to update the status to ready . 

**What did you expect to happen:**
The automatically created cluster role to have patch permissions . Currently it only has update permissions on volumesnapshotcontents/status.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

* `kubectl logs -f openebs-zfs-controller-f78f7467c-blr7q -n openebs -c openebs-zfs-plugin`
* `kubectl logs -f openebs-zfs-node-[xxxx] -n openebs -c openebs-zfs-plugin`
* `kubectl get pods -n openebs`
* `kubectl get zv -A -o yaml`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LocalPV-ZFS version: latest
- Kubernetes version (use `kubectl version`): v1.31.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):  Talos OS v1.8.3

**Comment by Abhinandan-Purkait** [comment]
Hi @Darkfella91 Thanks for reporting this, would you be interested in contributing this? You can add the `patch` verb change here https://github.com/openebs/zfs-localpv/blob/51972c4a5502abeb12a78460a87162c9bb75073b/deploy/helm/charts/templates/rbac.yaml#L104

**Comment by d4rkfella** [comment]
Sure thing, just opened a PR.
