### ISSUE TITLE
Cannot create ZFS volume due to outdated glibc

### ISSUE THREAD

**Issue by stevefan1999-personal** [openebs/zfs-localpv#67]
```
could not create volume rpool/k3s/openebs/pvc-9c375c67-4858-481e-ace4-83820f7221df cmd [create -o quota=4294967296 -o recordsize=4k -o dedup=off -o compression=on -o mountpoint=none rpool/k3s/openebs/pvc-9c375c67-4858-481e-ace4-83820f7221df] error: zfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /lib/libzfs.so.2)\n"
E0321 13:03:40.406946       1 volume.go:252] error syncing
```
I'm running on the latest Proxmox 6 with pre-populated data

**Comment by pawanpraka1** [comment]
@stevefan1999-personal, thanks for this issue. Can you please elaborate a little bit on your use ase to help us understand more.

**Comment by stevefan1999-personal** [comment]
@pawanpraka1 very simple: in the zfs plugin container pod you linked the libzfs from the host (in presumably bare metal environment), your host have a pretty new version of zfs (0.8) so it links with newer essential libraries (in this case glibc >= 2.28), and unfortunately the base environment in the container cannot support that new essential library (glibc == 2.24? starting from 19.04 ubuntu uses glibc >= 2.29), causing a missed dependency/symbol so that the zfs dataset/volume cannot be created, and thus not mounted.

**Comment by pawanpraka1** [comment]
@stevefan1999-personal , yes that is clear. Right not we support Ubuntu 18.04 only but the plan is to support for every other OS and their version. currently focus is to support it for Ubuntu and CentOS.

How do you want to use zfs-localpv in your case, what is the infra and setup are you looking for any specific feature? This project is in it's early stage and we need user feedback to put this project in the right direction.

**Comment by stevefan1999-personal** [comment]
@pawanpraka1 well I'm currently researching on OpenEBS -- right now I have single node but I might expand it later on, so I'm looking for sustainable development actually.

I know that zfs-localpv might not be the right thing but I'm curious to see its development, as I have used a similar local ZFS provisioner before. Now that I need volume snapshots and fine-grained control I considered it the time to upgrade.

BTW, I wonder if this project will grow to have NFS support? ZOL has a nice NFS share option with great OOTB experience.

**Comment by pawanpraka1** [comment]
Can you please raise an issue for NFS support? We will put it in our roadmap. Thanks for trying out zfs-localpv project .

**Comment by jemershaw** [comment]
I can confirm that everything works with 19.10 image -- if anyone wants to use it you can change your image to `jemershaw/zfs-driver:latest`

**Comment by pawanpraka1** [comment]
We have merged a PR https://github.com/openebs/zfs-localpv/pull/204 to make the ZFS operator yaml not agnostic to the underlying Operation system. Now we use the same Operator yaml (https://github.com/openebs/zfs-localpv/blob/master/deploy/zfs-operator.yaml) of all the Operating systems.
