### ISSUE TITLE
Invest on ZFS + NFS combination

### ISSUE THREAD

**Issue by stevefan1999-personal** [openebs/zfs-localpv#69]
Ditto as title, we could use ZFS and NFS with great experience.
Conceptual code:
```bash
# # Creates a ZFS dataset that automatically shares a NFS mount on /rpool/openebs/zfs-root
# zfs create -o sharenfs="@10.42.0.0/16,no_root_squash" rpool/openebs/zfs-root
# # Upsert any CIDRs required on the sharenfs options.
```

**Comment by orville-wright** [comment]
After multiple years of analyzing the NFS market and use-case within K8s, we feel that it's very unclear that NFS is a major use-case and significant consumer of K8s storage services for large enterprise storage applications in K8s. It seems that NFS users are the least understood of all storage users and we don't know what use-cases are driving NFS working k8s.

**Comment by sinhaashish** [comment]
As @orville-wright  tagged it as wont fix, i am closing this issue. Please feel free to reopen.
