### ISSUE TITLE
Auto provisioning with k3s

### ISSUE THREAD

**Issue by jemershaw** [openebs/zfs-localpv#72]
I am trying to use k3s to deploy the zfs-localpv but it seems like everytime I try to deploy https://github.com/openebs/zfs-localpv/blob/master/deploy/sample/fio.yaml I have to manually create the dataset on the zpool. I'm not sure if this is due to k3s removing most of the extra bits k8s have in it or not.

I also tried changing the provisioner to zfs-localpv vs zfs.csi.openebs.io and that didn't change anything. If this should work then I can try to debug further with my configuration.

**Comment by jemershaw** [comment]
I believe this is a zfs root problem because it can't find /sbin/zfs even though the md5sum is correct it just can't execute the binary.

**Comment by jemershaw** [comment]
It isn't a zfs root problem -- This is a glibc difference -- the container is using libc-2.27 but my host is using 2.28. Only solution around this for me would be to build the images using a different container.

**Comment by pawanpraka1** [comment]
@jemershaw , I guess you are facing this issue : https://github.com/openebs/zfs-localpv/issues/67. There is already PR for this https://github.com/openebs/zfs-localpv/pull/68. Just to confirm can you paste o/p of command "ldd `which zfs`". Also could you let us know what is your use case? How do you want to use zfs-locapv, what the setup and other details in this bug?

**Comment by jemershaw** [comment]
@pawanpraka1 Thanks -- That partially would fix my problem. I'm running void linux and it seems like the correct volume mounts would have to be like below.

```
docker run -it --rm --privileged -v /dev:/dev -v /sbin/zfs:/sbin/zfs -v /lib/libnvpair.so.1.0.1:/lib/libnvpair.so.1 -v /lib/libuutil.so.1.0.1:/lib/libuutil.so.1 -v /lib/libzfs.so.2.0.0:/lib/libzfs.so.2 -v /lib/libzfs_core.so.1.0.0:/lib/libzfs_core.so.1 -v /lib/libtirpc.so.3.0.0:/lib/libtirpc.so.3 -v /lib/libssl.so.47.0.6:/lib/libssl.so.47 -v /lib/libcrypto.so.45.0.5:/lib/libcrypto.so.45 -v /lib/libgssapi_krb5.so.2.2:/lib/libgssapi_krb5.so.2 -v /lib/libkrb5.so.3.3:/lib/libkrb5.so.3 -v /lib/libk5crypto.so.3.1:/lib/libk5crypto.so.3 -v /lib/libkrb5support.so.0.1:/lib/libkrb5support.so.0 ubuntu:19.04
```
I also testing the above with `ubuntu:19.10` and `ubuntu:rolling` and it works.
Host OS: `Void Linux`
Host Version: `5.4.19_1 #1 SMP PREEMPT Wed Feb 12 09:45:49 UTC 2020 x86_64 GNU/Linux`
Host glibc: `glibc-2.30_1`

Please let me know once #68 image is pushed upstream and I can verify.

**Comment by pawanpraka1** [comment]
@jemershaw, jfyi PR https://github.com/openebs/zfs-localpv/pull/68 has been merged.

**Comment by pawanpraka1** [comment]
@jemershaw  Can you see if this yaml fixes the issue. This is still a work in progress(https://github.com/openebs/zfs-localpv/pull/134), let me know your feedback 
https://raw.githubusercontent.com/pawanpraka1/zfs-localpv/lib/deploy/zfs-operator.yaml

**Comment by pawanpraka1** [comment]
We have merged a PR https://github.com/openebs/zfs-localpv/pull/204 to make the ZFS operator yaml not agnostic to the underlying Operation system. Now we use the same Operator yaml 9https://github.com/openebs/zfs-localpv/blob/master/deploy/zfs-operator.yaml) of all the Operting systems.
