### ISSUE TITLE
Support for storage on BSD/FreeNAS

### ISSUE THREAD

**Issue by platten** [openebs/zfs-localpv#74]
Hello,

It would be great to be able to install zfs-localpv as part of a FreeNAS plugin, and have it provision/manage storage for Kubernetes cluster. It would be so much cleaner than using the iSCSI  https://github.com/travisghansen/freenas-iscsi-provisioner or NFS https://github.com/nmaupu/freenas-provisioner solutions out there.

Thanks,
Paul

**Comment by kmova** [comment]
@platten, thank you for suggesting this!  It would be great to add it. 

Could you please explain the use case a little more? How do you foresee using FreeNAS with Kubernetes? For instance:
(a) Will FreeNAS be installed within K8s cluster, on the Kubernetes worker node (or)
(b) Use it as Out of cluster mode.

**Comment by platten** [comment]
Hello Kiran, I would see FreeNAS sitting outside of K8s and providing storage services for the K8s cluster (with a control plane/API running on K8s to request provisioning from FreeNAS and connect the storage to the pods).

**Comment by kmova** [comment]
If FreeNAS is running outside of the cluster, the Kubernetes worker node will need to access the storage over the network. It has to be either NFS or iSCSI or any other protocol that FreeNAS supports. 

- control plane (CSI driver) will run on K8s - manage the provisioning of volume. 
- node component ( CSI driver) also running on K8s - will have to attach/detach the volume using either NFS or iSCSI. 

(what am I missing?)

**Comment by sinhaashish** [comment]
Labelling it as enhancement as this needs some dev effort.

**Comment by Abhinandan-Purkait** [comment]
@platten We do not have any infra to support the testing on these. Also we don't take up any vendor integration as per our VISION. Please refer to the  out-of-scope section for the same. Please feel free to open if you feel otherwise.

https://github.com/openebs/community/blob/develop/VISION.md

**Comment by Abhinandan-Purkait** [comment]
Closing this as it's out of scope as per VISION. https://github.com/openebs/community/blob/develop/VISION.md
