### ISSUE TITLE
pod restarts on a loaded setup seen to cause data loss. 

### ISSUE THREAD

**Issue by w3aman** [openebs/zfs-localpv#88]
I have 200s of zfs-Local persistent volumes. After restarting the application pods in some of the pods (in my case 4) data is lost which i dumped in starting.
When i retried the whole scenario i didn't hit this issue at this point where i am restarting the pods with parent volumes. I have the snapshot for the volumes. when i cloned the volume and restarted all application pods (consuming parent volume + cloned volumes) some of the pod which were of cloned volumes (in my case only one) hitted the issue of data being lost.

After digging the setup found this.
`
43212 time="2020-04-21T17:01:06Z" level=error msg="zfspv: failed to remove mount path Error: unlinkat /var/lib/kubelet/pods/2f9fe907-53b9-46c0-9b9b-d6bed9467836/volumes/      kubernetes.io~csi/pvc-8120d443-c6a7-4f2a-9240-05deb3e05850/mount: device or resource busy"
`

Looks like when we unmounted the volume,but meanwhile system umount is in progress, which we are not aware, and we proceeded to delete the mount path, which deleted the files there.

**Note:** if any further info required , let me know !

**Comment by pawanpraka1** [comment]
When you change the mountpoint property to none, ZFS automatically umounts the file system.     When we delete the pod, we get the unmount request for the old pod and mount requets for the new pod. When unmount is done by the driver and system is slow in processing the umount request for the volume, the driver assumes that unmount has done and proceeded to delete the mountpath,
as unmount has not done completely, the driver will delete the data as part of cleaning up for the NodeUnPublish request.

fix is under review : https://github.com/openebs/zfs-localpv/pull/89

**Comment by pawanpraka1** [comment]
steps for getting into this issue :
1.  deploy pod with zfs volume
2.  restart pod
3.  old pod's unmount done for the moountpath, but system is slow in processing it
4.  zfs driver is not aware that system is still processing the unmount request. The driver will procedd to delete the old mountpath and it will use os-removeall which will delete the data also as removeall will delete everything inside the mountpath and there will be dataloss.
